# Generated by Django 2.2.6 on 2021-12-22 20:16

from django.db import migrations, models
import foodgram.validation


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211220_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='quantity',
        ),
        migrations.AddField(
            model_name='quantity',
            name='amount',
            field=models.FloatField(default=0, validators=[foodgram.validation.validate_under_zero], verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('г', 'Грамм'), ('кг', 'Килограмм'), ('Ст.л.', 'Столовая ложка'), ('мл', 'Миллилитр'), ('л', 'Литр'), ('шт', 'Штука'), ('по вкусу', 'По вкусу'), ('ч.л.', 'Чайная ложка'), ('капля', 'Капля'), ('горсть', 'Горсть'), ('стакан', 'Стакан'), ('кусок', 'Кусок'), ('банка', 'Банка'), ('щепотка', 'Щепотка')], default='г', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[foodgram.validation.validate_under_zero], verbose_name='Время приготовления'),
        ),
    ]
