# Generated by Django 2.2.6 on 2021-12-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20211228_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=20, unique=True, verbose_name='Цвет'),
        ),
    ]
